<?php
/**
 * @file
 * Allows login using different social networking services
 */

use \Drupal\Core\Form\FormStateInterface;

function social_auth_theme() {
  return array(
    'login_with' => array(
      'variables' => array('social_networks' => NULL)
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function social_auth_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['social_api_auth'] = array(
    '#theme' => 'login_with',
    '#weight' => 100,
  );
}

/**
 * Implements hook_preprocess_HOOK()
 */
function social_auth_preprocess_login_with(&$variables) {
  $variables['social_networks'] = \Drupal::config('social_api.settings')->get('auth');

  $variables['base_path'] = base_path();
}
