<?php

/**
 * @file
 * Allows login using different social networking services.
 */

/**
 * Implements hook_theme().
 */
function social_auth_theme() {
  return [
    'login_with' => [
      'variables' => ['social_networks' => NULL, 'destination' => NULL],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function social_auth_preprocess_login_with(&$variables) {
  $request = \Drupal::request();
  if ($request->query->has('destination')) {
    $variables['destination'] = $request->query->get('destination');
  }
  $variables['base_path'] = base_path();
}
